name: cat_breeds_app
description: "A Flutter app to explore and learn about different cat breeds"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^15.1.2
  flutter_svg: ^2.1.0

  # Riverpod
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: 6.9.5

  # Riverpod
  riverpod_generator: 2.6.5
  riverpod_lint: 2.6.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
